### ISSUE TITLE
Release Binary Crash on win10, debug compiled point at pipeline creation fail: No message at all

### ISSUE THREAD

**Issue by Kuranes** [GPUOpen-Effects/Hybrid-Shadows#1]
in ShadowRaytracer.cpp: 187

![image](https://user-images.githubusercontent.com/128571/116661959-77333d00-a995-11eb-91ee-c0801bc3356f.png)

-  GPU is nvidia 1070 
- other sample like gtlf sample 1.4 works, both binary and locally compiled
- it works on nvidia 2080 so must be a DXR limitation

**Comment by nicovanbentum** [comment]
Might be related, I had a similar issue where m_pClassifyPso[0] failed to compile, had to update Windows from 1909 to 20H2.

**Comment by rys** [comment]
We've triaged the failure on Pascal-based GPUs and will have a fix in the next update to allow it to fail gracefully.
